from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .config import FactoryConfig


@dataclass(frozen=True)
class BackendResult:
    returncode: int
    stdout: str
    stderr: str
    outputs: dict[str, str]


def run_backend(
    config: FactoryConfig,
    repo_root: Path,
    run_dir: Path,
    role: str,
    job: dict[str, Any],
) -> BackendResult:
    if config.backend == "fake_planner":
        return _run_fake_backend(role, job)
    if config.backend == "codex_exec":
        return _run_codex_exec(config, repo_root, run_dir, role, job)
    raise ValueError(f"unsupported backend: {config.backend}")


def _run_fake_backend(role: str, job: dict[str, Any]) -> BackendResult:
    output_name = _role_output_name(role)
    content = "\n".join(
        [
            f"# {role.replace('_', ' ').title()}",
            "",
            f"Job: {job['id']}",
            "",
            "Generated by fake backend for tests.",
            "",
        ]
    )
    if role == "task_generator":
        output_name = "tasks/001-chartpatch-plan.md"
        content = "\n".join(
            [
                "# Task 001: chartpatch plan",
                "",
                "Generated by fake backend for tests.",
                "",
            ]
        )
    return BackendResult(
        returncode=0,
        stdout=f"fake backend generated {output_name}\n",
        stderr="",
        outputs={output_name: content},
    )


def _run_codex_exec(
    config: FactoryConfig,
    repo_root: Path,
    run_dir: Path,
    role: str,
    job: dict[str, Any],
) -> BackendResult:
    prompt = _render_prompt(repo_root, run_dir, role, job)
    output_capture = run_dir / "agents" / f"{role}.{job['id']}.last-message.md"
    args = [
        item.format(repo=str(repo_root), run=str(run_dir), role=role, job=job["id"])
        for item in config.backend_config.args
    ]
    command = [
        config.backend_config.command,
        *args,
        "--sandbox",
        "read-only",
        "-o",
        str(output_capture),
        prompt,
    ]
    completed = subprocess.run(command, text=True, capture_output=True)
    outputs = {}
    if completed.returncode == 0 and output_capture.exists():
        outputs[_role_output_name(role)] = output_capture.read_text(encoding="utf-8")
    return BackendResult(
        returncode=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
        outputs=outputs,
    )


def _render_prompt(repo_root: Path, run_dir: Path, role: str, job: dict[str, Any]) -> str:
    prompt_path = repo_root / "agents" / f"{role.replace('_', '-')}.md"
    template = prompt_path.read_text(encoding="utf-8")
    return template.format(
        repo=repo_root,
        run=run_dir,
        job_id=job["id"],
        feature=run_dir / "input" / "feature.md",
        config=run_dir / "input" / "factory.yaml",
        plan=run_dir / "plan.md",
        architecture=run_dir / "architecture.md",
        tasks=run_dir / "tasks",
        output=run_dir / _role_output_name(role),
    )


def _role_output_name(role: str) -> str:
    if role == "planner":
        return "plan.md"
    if role == "architect":
        return "architecture.md"
    if role == "task_generator":
        return "tasks/001-chartpatch-plan.md"
    raise ValueError(f"no output mapping for role: {role}")
